{
 "title": "Weather History",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  temperature\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 0 },
   "format": "celsius",
   "valueName": "range",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  temperature\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Max Temperature",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "format": "celsius",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  temperature\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Min Temperature",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "format": "celsius",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  temperature\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Alters",
   "type": "alertlist",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  temperature\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  temperature\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Max Humidity",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  humidity\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Min Humidity",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  humidity\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  temperature\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pressure\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  humidity\nFROM measure\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}